### ISSUE TITLE
Improvement on Polymake_V_Rep_command_string (and similar for H_Rep)

### ISSUE THREAD

**Issue by HereAround** [homalg-project/ToricVarieties_project#141]
As noted by @fingolfin in https://github.com/oscar-system/JToric.jl/pull/38:

> However, it also seems as if your function Polymake_V_Rep_command_string constantly creates new Polymake objects? Is there a reason why you don't just create one of these once, and keep it around? Or am I misunderstanding the code?

This should be changed into an attribute.

**Comment by fingolfin** [comment]
It may not need to be a full attribute; you can just store it as another component in your `IsPolymakePolytope` objects: Right now, `Polymake_V_Rep_command_string` reads e.g. `poly!.rep_type` and others. You then do things like e.g.
```gap
        command_string := Concatenation( Polymake_V_Rep_command_string( poly ), ".VERTICES" );
        JuliaEvalString( command_string );
        s := JuliaToGAP( IsString, Julia.string( Julia.PolytopeByGAP4PackageConvex ) );
        res_string := SplitString( s, '\n' );
        res_string := List( [ 2 .. Length( res_string ) ], i -> Concatenation( "[", ReplacedString( res_string[ i ], " ", "," ), "]" ) );
        vertices := EvalString( Concatenation( "[", JoinStringsWithSeparator( res_string, "," ), "]" ) );
```

If you instead constructed the polytope in Julia once and stored it as, say, `poly!.julia_poly`, this could become something like this, which is both simpler and more efficient:
```gap
        vertices := JuliaToGAP( IsList, pm.VERTICES(poly!.julia_poly), true );
```
Note that I didn't check if the function really is called `VERTICES` in `Polymake.jl`, but the gist should be clear anyway. And in any case, please consider using Oscar polytopes instead of "raw" polytopes from `Polymake.jl` -- you can always fall back to them if something is not yet made available via a "native" Oscar API (in that case, probably a good idea to request the missing API, too

**Comment by HereAround** [comment]
Thank you @fingolfin .

It appears that most tests of https://github.com/oscar-system/JToric.jl/pull/38 fails, because you already removed `JuliaEvalString`. I am hence trying to fix this now, and I am struggling to create the objects in questions (polytopes, cones).

Example:
The string that I evaluated with `JuliaEvalString`:
"ConeByGAP4PackageConvex = Polymake.polytope.Cone( INPUT_RAYS = [ 1 0; 0 1] )"

I am trying to replace this with something like:
> POLYMAKE_JULIA_MODULE.polytope.Cone( INPUT_RAYS = rays );

This does not seem to work:
1. `Error, Variable: 'INPUT_RAYS' must have a value`.
2. The GAP-list `rays` must be turned into a corresponding `Julia` object.

I already tried a couple of things (none of which works, so no need to list them here).

**Comment by fingolfin** [comment]
> because you already removed `JuliaEvalString`

Huh, what are you talking about?

**Comment by fingolfin** [comment]
I have not removed JuliaEvalString and have no plans to do so. And even if I did, that would not affect existing releases of  GAP.jl. So whatever problem you are encountering, it's not caused by that

**Comment by HereAround** [comment]
Sorry, my bad. I confused this with `ImportJuliaModuleIntoGAP`. I'll investigate more what triggers these failures then.

On this very issue - I am having trouble to remove `JuliaEvalString` from `JConvex` because I fail to create the corresponding objects (cones, polytopes) without invoking `JuliaEvalString`.

Example:
For the cone generated by [1,0] and [0,1], I thus far passed the following String to `JuliaEvalString`:

"ConeByGAP4PackageConvex = Polymake.polytope.Cone( INPUT_RAYS = [ 1 0; 0 1] )"

Now, it would seem that this should be replaced by:

> POLYMAKE_JULIA_MODULE.polytope.Cone( INPUT_RAYS = rays );

This does not work in this form:
1. `Error, Variable: 'INPUT_RAYS' must have a value`.
2. Presumably, the GAP-list `rays` must be converted to Julia.

This may be something very simple, but after trying various things, I am still without solution. Suggestions very much appreciated.

**Comment by fingolfin** [comment]
First, let me point out that it is not necessary to remove *all* uses of `JuliaEvalString`; while it is always possible, it can simply be most convenient to use it here and there! It can indeed be perfectly fine for short fixed pieces of code, and in fact, I'll use it below.

What I object to is assembling long strings of code and then running them through `JuliaEvalString`. This is hard to debug, easy to mess up, it usually requires more code, and is slower.

Now to your concrete questions: of course I know nothing about what this code actually does, so the first thing I did was to do a sanity check and see what happens if I try to do that in Julia. So, I verified that this works fine (which it does):
```julia
Polymake.polytope.Cone(INPUT_RAYS = [ 1 0; 0 1] )
```
Note that this uses a keyword argument, and GAP has no keyword arguments, so calling it from the GAP side is more of a hassle. We provide a helper function for it in GAP.jl, though: `CallJuliaFunctionWithKeywordArguments`. Before we get to that, we also need to convert the matrix. Now, I'll show you a way, but in practice it matters where you matrices come from; it may very well be easier to manage them as Julia matrices from the start!

To convert GAP objects to Julia, the first impulse is to use `GAPToJulia`; but that gives us a `Vector{Vector{Any}}` here:
```
gap> GAPToJulia([[1,0],[0,1]]);
<Julia: Any[Any[1, 0], Any[0, 1]]>
```
Indeed, it is impossible for GAP to know what type you want, there are many possibilities: e.g. a `Matrix{int}` or a `Matrix{BigInt}` or a `Vector{Vector{Int}}` or ... We just have to tell it. We need the desired Julia type for that -- here for now I'll assume that means `Matrix{Int}`, simply because that's what the Julia example above used.
```
gap> JuliaMatrixInt:=JuliaEvalString( "Matrix{Int}" );;
gap> M := JuliaMatrixInt([[1,0],[0,1]]);
<Julia: [1 0; 0 1]>
gap> Julia.typeof(M);
<Julia: Matrix{Int64}>
```
Note that I used `JuliaEvalString`, but I used it on a fixed input that you can see in full; and the output stays constant -- in fact I would compute it only once and then cache it. (In the future, we'll probably add another helper function to GAP.jl to make it nicer to instantiate such types, but for now, `JuliaEvalString` does the job just fine).

Let's put it all together:
```
gap> cone:=CallJuliaFunctionWithKeywordArguments(Julia.Polymake.polytope.Cone,[],rec(INPUT_RAYS:=M));<Julia: Polymake.BigObjectAllocated(Ptr{Nothing} @0x00007fb37aaf2100)>
gap> Julia.display(cone);;
type: Cone<Rational>

INPUT_RAYS
        1 0
        0 1

```

But let me once again recommend to use Oscar's Cone API, not the one from Polymake.jl. I.e., in Julia:
```
julia> using Oscar

julia> cone = Cone([1 0 ; 0 1])
A polyhedral cone in ambient dimension 2

```
which translates to this GAP code:
```
gap> JuliaMatrixInt:=JuliaEvalString( "Matrix{Int}" );;
gap> M := JuliaMatrixInt([[1,0],[0,1]]);
<Julia: [1 0; 0 1]>
gap> cone := Julia.Cone(M);
<Julia: A polyhedral cone in ambient dimension 2>
```

**Comment by HereAround** [comment]
Thank you for elaborating @fingolfin . I'll try to adjust `JConvex` accordingly.

**Comment by fingolfin** [comment]
Note that I believe that eventually, it would be possible (and perhaps even *easier*) to completely replace `JConvex` with pure Julia code. That is, instead of writing GAP methods that call out to Julia, just re-write those methods in Julia, then use `GAP.Globals.InstallMethod` on those methods. I.e. instead of this
```gap
InstallMethod( IsPointed,
               [ IsCone ],
    function( cone )
    
    if PolymakeAvailable() then
        return Polymake_IsPointed( ExternalPolymakeCone( cone ) );
    fi;
    
    TryNextMethod();
    
end );
```
you might as well write this in Julia (e.g. as part of `JToric`); note that here I assume that `ExternalPolymakeCone` will be implemented as a trivial method that does something like `cone -> cone!.julia_rep` which is bound to an Oscar.jl `Cone` object...)
```julia
module JConvex
using GAP

@gapwrap InstallMethod(opr::Union{String,GapObj}, filter::Vector{GapObj}, method::Function) = GAP.Globals.InstallMethod(GapObj(opr), GapObj(filter), method)

function __init__()
  local IsCone = GAP.Globals.IsCone
  InstallMethod( GAP.Globals.IsPointed, [ IsCone ],
    function( cone::GapObj )
       return ispointed( ExternalPolymakeCone( cone ) )
    end )
   # TODO: install many more methods
end
```

Also, more code should be added to `Oscar.jl` / `Polymake.jl`: E.g. I just noticed this method in `JConvex:
```gap
InstallMethod( Polymake_Intersection,
               "construct intersection of two cones",
               [ IsPolymakeCone, IsPolymakeCone ],
  function( cone1, cone2 )
    local cone1_h, cone2_h, new_ineqs, new_equ;
    
    cone1_h := Polymake_H_Rep( cone1 );
    cone2_h := Polymake_H_Rep( cone2 );
    
    new_ineqs := Concatenation( cone1_h!.inequalities, cone2_h!.inequalities );
    new_equ := Concatenation( cone1_h!.equalities, cone2_h!.equalities );
    
    return Polymake_ConeFromInequalities( new_ineqs, new_equ );
    
end );
```

I don't see an `intersect` method for cones in Oscar.jl right now, but I am sure Polymake can do it (right, @lkastner?), if necessary by using similar code as yours above. With that, I would expect the above method to simply become something like this:
```gap
InstallMethod( Polymake_Intersection,
               "construct intersection of two cones",
               [ IsPolymakeCone, IsPolymakeCone ],
  function( cone1, cone2 )
    return NewPolymakeCone( Julia.intersect( ExternalPolymakeCone( cone1 ), ExternalPolymakeCone( cone2 ) ) );
end );
```
or similarly when written in pure Julia...

**Comment by lkastner** [comment]
Like this?
```
julia> c0 = Polymake.polytope.Cone(INPUT_RAYS=[1 0; 0 1]);

julia> c1 = Polymake.polytope.Cone(INPUT_RAYS=[-1 1; 1 1]);

julia> c01 = Polymake.polytope.intersection(c0, c1);

julia> c01.RAYS
pm::Matrix<pm::Rational>
1 1
0 1
```

**Comment by fingolfin** [comment]
This can be closed, Polymake_V_Rep_command_string is no more

**Comment by HereAround** [comment]
Thank you @fingolfin .
