### ISSUE TITLE
ToricVarieties: Dependency on Convex is not optional

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/ToricVarieties_project#99]
If I try to load `ToricVarieties` without `NConvex`, I get the following error:
```
Error, Variable: 'IsConvexObject' must have a value
not in any function at ~/.gap/pkg/ToricVarieties_project/ToricVarieties/gap/ToricVarieties.gd:435
```
Additionally, the version `2021.04-24` of `NConvex` required by `Convex` is not available in the homalg CI, since we use the version here: https://github.com/homalg-project/NConvex Maybe we could simply remove `ToricVarieties` from the homalg CI now that `ToricVarieties_project` has its own CI?

**Comment by HereAround** [comment]
Thank you for pointing out this critical issue. On second thought - I am actually a bit surprised that the tests in the `ToricVarieties_project` completely yesterday.

Since this new version for `NConvex` is a hot-fix to get (temporarily) around `CddInterface` and `NormalizInterface` not being available in Julia, I suggest the following:
1. I add `NConvex` with version `2020.11-04` again as needed package for `ToricVarieties`.
2. You keep `ToricVarieties` in the homalg CI. It probably does not hurt to test it twice. And, for all it is worth, you will immediately detect if changes in `homalg` lead to problems in `ToricVarieties`.

What do you think?

**Comment by HereAround** [comment]
I believe this should fix this issue: https://github.com/homalg-project/ToricVarieties_project/pull/100

**Comment by HereAround** [comment]
I have merged this change into the master (and made it into a new release for the Gap distribution system). Please report back if this still causes issues with the `homalg` CI.

**Comment by zickgraf** [comment]
Our CI is green again, so I will close the issue :-)

> On second thought - I am actually a bit surprised that the tests in the ToricVarieties_project completely yesterday.

In your CI an older version of `NConvex` is loaded as an optional dependency of `GradedRingForHomalg`. This does not happen in our CI because of other dependencies down the road (we only have a very old `CddInterface` installed).
